# Generated by Django 6.0.3 on 2026-03-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema/Serviço')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início da Execução')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('pecas_substituidas', models.TextField(blank=True, verbose_name='Peças Substituídas')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('imagem_manutencao', models.ImageField(blank=True, null=True, upload_to='manutencoes/imagens/', verbose_name='Foto da Manutenção')),
                ('relatorio', models.FileField(blank=True, null=True, upload_to='manutencoes/relatorios/', verbose_name='Relatório')),
                ('observacoes_conclusao', models.TextField(blank=True, verbose_name='Observações de Conclusão')),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot', verbose_name='Robô')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnico', verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
