# Generated by Django 6.0.3 on 2026-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Robô')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('fabricante', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série (Ativo)')),
                ('patrimonio', models.CharField(blank=True, max_length=100, verbose_name='Patrimônio')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('localizacao', models.CharField(blank=True, max_length=300, verbose_name='Localização')),
                ('grupo', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('alocacao', models.CharField(blank=True, max_length=200, verbose_name='Alocação/Cliente')),
                ('status_operacional', models.CharField(choices=[('operacional', 'Operacional'), ('em_manutencao', 'Em manutenção'), ('parado', 'Parado'), ('em_inspecao', 'Em inspeção'), ('inativo', 'Inativo')], default='operacional', max_length=20, verbose_name='Status Operacional')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='robots/imagens/', verbose_name='Imagem')),
                ('documento_tecnico', models.FileField(blank=True, null=True, upload_to='robots/documentos/', verbose_name='Documento Técnico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robô',
                'verbose_name_plural': 'Robôs',
                'ordering': ['nome'],
            },
        ),
    ]
