# Generated by Django 6.0.3 on 2026-03-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='Matrícula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('especialidade', models.CharField(choices=[('mecanica', 'Mecânica'), ('eletrica', 'Elétrica'), ('eletronica', 'Eletrônica'), ('programacao', 'Programação/Software'), ('hidraulica', 'Hidráulica'), ('pneumatica', 'Pneumática'), ('inspecao', 'Inspeção Robótica'), ('geral', 'Manutenção Geral')], default='geral', max_length=50, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de acesso')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nome'],
            },
        ),
    ]
